//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Localization.Strings.ToolPage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Localization.Strings.ToolPage.ToolPage", typeof(ToolPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFileType {
            get {
                return ResourceManager.GetString("AllFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tool to suggest.
        /// </summary>
        public static string NoSmartDetectedTool {
            get {
                return ResourceManager.GetString("NoSmartDetectedTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to another tool.
        /// </summary>
        public static string SendToSmartDetection {
            get {
                return ResourceManager.GetString("SendToSmartDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle keep the window on top (Ctrl+Up).
        /// </summary>
        public static string ToggleCompactOverlayTooltip {
            get {
                return ResourceManager.GetString("ToggleCompactOverlayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open this file.
        /// </summary>
        public static string UnableOpenFile {
            get {
                return ResourceManager.GetString("UnableOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the file &apos;{0}&apos;. Only textual files can be opened..
        /// </summary>
        public static string UnableOpenFileDescription {
            get {
                return ResourceManager.GetString("UnableOpenFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save this file.
        /// </summary>
        public static string UnableSaveFile {
            get {
                return ResourceManager.GetString("UnableSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the file &apos;{0}&apos;. Check the logs to see the internal error..
        /// </summary>
        public static string UnableSaveFileDescription {
            get {
                return ResourceManager.GetString("UnableSaveFileDescription", resourceCulture);
            }
        }
    }
}
