//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Blazor.BuiltInGroups {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Groups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Groups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Blazor.BuiltInGroups.Groups", typeof(Groups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converters.
        /// </summary>
        internal static string ConvertersGroupAccessibleName {
            get {
                return ResourceManager.GetString("ConvertersGroupAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converters.
        /// </summary>
        internal static string ConvertersGroupDisplayTitle {
            get {
                return ResourceManager.GetString("ConvertersGroupDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoders and decoders.
        /// </summary>
        internal static string EncodersDecodersGroupAccessibleName {
            get {
                return ResourceManager.GetString("EncodersDecodersGroupAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoders / Decoders.
        /// </summary>
        internal static string EncodersDecodersGroupDisplayTitle {
            get {
                return ResourceManager.GetString("EncodersDecodersGroupDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatters.
        /// </summary>
        internal static string FormattersGroupAccessibleName {
            get {
                return ResourceManager.GetString("FormattersGroupAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatters.
        /// </summary>
        internal static string FormattersGroupDisplayTitle {
            get {
                return ResourceManager.GetString("FormattersGroupDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generators.
        /// </summary>
        internal static string GeneratorsGroupAccessibleName {
            get {
                return ResourceManager.GetString("GeneratorsGroupAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generators.
        /// </summary>
        internal static string GeneratorsGroupDisplayTitle {
            get {
                return ResourceManager.GetString("GeneratorsGroupDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic.
        /// </summary>
        internal static string GraphicGroupAccessibleName {
            get {
                return ResourceManager.GetString("GraphicGroupAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic.
        /// </summary>
        internal static string GraphicGroupDisplayTitle {
            get {
                return ResourceManager.GetString("GraphicGroupDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testers.
        /// </summary>
        internal static string TestersGroupAccessibleName {
            get {
                return ResourceManager.GetString("TestersGroupAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testers.
        /// </summary>
        internal static string TestersGroupDisplayTitle {
            get {
                return ResourceManager.GetString("TestersGroupDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextGroupAccessibleName {
            get {
                return ResourceManager.GetString("TextGroupAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextGroupDisplayTitle {
            get {
                return ResourceManager.GetString("TextGroupDisplayTitle", resourceCulture);
            }
        }
    }
}
