
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Toolkit.Mvvm.ComponentModel;
using System.ComponentModel;
using System.Globalization;
using Windows.ApplicationModel.Resources;
using Windows.Globalization;
using Windows.UI.Xaml;

namespace DevTools.Localization
{
    public partial class LanguageManager : ObservableObject
    {
        private static LanguageManager _languageManager;
		
        private readonly Base64EncoderDecoderStrings _base64encoderdecoder = new Base64EncoderDecoderStrings();
        private readonly MainPageStrings _mainpage = new MainPageStrings();
        private readonly SettingsStrings _settings = new SettingsStrings();

        /// <summary>
        /// Gets an instance of <see cref="LanguageManager"/>.
        /// </summary>
        public static LanguageManager Instance => _languageManager ?? (_languageManager = new LanguageManager());

        /// <summary>
        /// Gets if the text must be written from left to right or from right to left.
        /// </summary>
        public FlowDirection FlowDirection { get; private set; }

        /// <summary>
        /// Gets the <see cref="Base64EncoderDecoderStrings"/>.
        /// </summary>
        public Base64EncoderDecoderStrings Base64EncoderDecoder => _base64encoderdecoder;

        /// <summary>
        /// Gets the <see cref="MainPageStrings"/>.
        /// </summary>
        public MainPageStrings MainPage => _mainpage;

        /// <summary>
        /// Gets the <see cref="SettingsStrings"/>.
        /// </summary>
        public SettingsStrings Settings => _settings;

        /// <summary>
        /// Retrieves the current culture.
        /// </summary>
        public CultureInfo GetCurrentCulture()
        {
            return CultureInfo.CurrentUICulture;
        }

        /// <summary>
        /// Change the current culture of the application
        /// </summary>
        public void SetCurrentCulture(CultureInfo culture)
        {
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;
            ApplicationLanguages.PrimaryLanguageOverride = culture.TextInfo.CultureName;

            if (culture.TextInfo.IsRightToLeft)
            {
                FlowDirection = FlowDirection.RightToLeft;
            }
            else
            {
                FlowDirection = FlowDirection.LeftToRight;
            }

            // All the properties changed.
            OnPropertyChanged(new PropertyChangedEventArgs(string.Empty));
        }
    }

    public class Base64EncoderDecoderStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("DevTools.Localization/Base64EncoderDecoder");

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");
    }

    public class MainPageStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("DevTools.Localization/MainPage");

        /// <summary>
        /// Gets the resource Yes.
        /// </summary>
        public string Yes => _resources.GetString("Yes");
    }

    public class SettingsStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("DevTools.Localization/Settings");

        /// <summary>
        /// Gets the resource DisplayName.
        /// </summary>
        public string DisplayName => _resources.GetString("DisplayName");
    }
}