//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Tools.Tools.Text.AnalyzerAndUtilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnalyzerAndUtilities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyzerAndUtilities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Tools.Tools.Text.AnalyzerAndUtilities.AnalyzerAndUtilities", typeof(AnalyzerAndUtilities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text analyzer, converter and utilities tool.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of treatments to apply to the input text. Actions are performed in the order they&apos;re set..
        /// </summary>
        internal static string ActionsOptionDescription {
            get {
                return ResourceManager.GetString("ActionsOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetize.
        /// </summary>
        internal static string Alphabetize {
            get {
                return ResourceManager.GetString("Alphabetize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetize by last word.
        /// </summary>
        internal static string AlphabetizeLast {
            get {
                return ResourceManager.GetString("AlphabetizeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aLtErNaTiNg cAsE.
        /// </summary>
        internal static string AlternatingCase {
            get {
                return ResourceManager.GetString("AlternatingCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camelCase.
        /// </summary>
        internal static string CamelCase {
            get {
                return ResourceManager.GetString("CamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character frequency.
        /// </summary>
        internal static string CharacterFrequency {
            get {
                return ResourceManager.GetString("CharacterFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COBOL-CASE.
        /// </summary>
        internal static string CobolCase {
            get {
                return ResourceManager.GetString("CobolCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSTANT_CASE.
        /// </summary>
        internal static string ConstantCase {
            get {
                return ResourceManager.GetString("ConstantCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert case.
        /// </summary>
        internal static string ConvertCase {
            get {
                return ResourceManager.GetString("ConvertCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert line break.
        /// </summary>
        internal static string ConvertEndOfLineSequence {
            get {
                return ResourceManager.GetString("ConvertEndOfLineSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze text and provide some basic utility tools.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line break.
        /// </summary>
        internal static string EndOfLineSequence {
            get {
                return ResourceManager.GetString("EndOfLineSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR (\r).
        /// </summary>
        internal static string EndOfLineSequenceCR {
            get {
                return ResourceManager.GetString("EndOfLineSequenceCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRLF (\r\n).
        /// </summary>
        internal static string EndOfLineSequenceCRLF {
            get {
                return ResourceManager.GetString("EndOfLineSequenceCRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF (\n).
        /// </summary>
        internal static string EndOfLineSequenceLF {
            get {
                return ResourceManager.GetString("EndOfLineSequenceLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        internal static string EndOfLineSequenceMixed {
            get {
                return ResourceManager.GetString("EndOfLineSequenceMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string EndOfLineSequenceUnknown {
            get {
                return ResourceManager.GetString("EndOfLineSequenceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file selected doesn&apos;t exist..
        /// </summary>
        internal static string InputFileNotFound {
            get {
                return ResourceManager.GetString("InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text or path to a file to treat..
        /// </summary>
        internal static string InputOptionDescription {
            get {
                return ResourceManager.GetString("InputOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an input text or an input file.
        /// </summary>
        internal static string InvalidInputOrFileCommand {
            get {
                return ResourceManager.GetString("InvalidInputOrFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InVeRsE CaSe.
        /// </summary>
        internal static string InverseCase {
            get {
                return ResourceManager.GetString("InverseCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kebab-case.
        /// </summary>
        internal static string KebabCase {
            get {
                return ResourceManager.GetString("KebabCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Analyzer and Utilities.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lower case.
        /// </summary>
        internal static string LowerCase {
            get {
                return ResourceManager.GetString("LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the output file.
        /// </summary>
        internal static string OutputFileOptionDescription {
            get {
                return ResourceManager.GetString("OutputFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraphs.
        /// </summary>
        internal static string Paragraphs {
            get {
                return ResourceManager.GetString("Paragraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PascalCase.
        /// </summary>
        internal static string PascalCase {
            get {
                return ResourceManager.GetString("PascalCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raNdoM cASe.
        /// </summary>
        internal static string RandomCase {
            get {
                return ResourceManager.GetString("RandomCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        internal static string Randomize {
            get {
                return ResourceManager.GetString("Randomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse alphabetize.
        /// </summary>
        internal static string ReverseAlphabetize {
            get {
                return ResourceManager.GetString("ReverseAlphabetize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse alphabetize by last word.
        /// </summary>
        internal static string ReverseAlphabetizeLast {
            get {
                return ResourceManager.GetString("ReverseAlphabetizeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string SelectionColumnNumber {
            get {
                return ResourceManager.GetString("SelectionColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End position.
        /// </summary>
        internal static string SelectionEndPosition {
            get {
                return ResourceManager.GetString("SelectionEndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string SelectionLength {
            get {
                return ResourceManager.GetString("SelectionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string SelectionLineNumber {
            get {
                return ResourceManager.GetString("SelectionLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start position.
        /// </summary>
        internal static string SelectionStartPosition {
            get {
                return ResourceManager.GetString("SelectionStartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string SelectionStatistics {
            get {
                return ResourceManager.GetString("SelectionStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence case.
        /// </summary>
        internal static string SentenceCase {
            get {
                return ResourceManager.GetString("SentenceCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentences.
        /// </summary>
        internal static string Sentences {
            get {
                return ResourceManager.GetString("Sentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer &amp; Utilities.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show original text.
        /// </summary>
        internal static string ShowOriginalText {
            get {
                return ResourceManager.GetString("ShowOriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snake_case.
        /// </summary>
        internal static string SnakeCase {
            get {
                return ResourceManager.GetString("SnakeCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort lines.
        /// </summary>
        internal static string SortLines {
            get {
                return ResourceManager.GetString("SortLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string StatisticTitle {
            get {
                return ResourceManager.GetString("StatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string StatisticValue {
            get {
                return ResourceManager.GetString("StatisticValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextInput {
            get {
                return ResourceManager.GetString("TextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextStatistics {
            get {
                return ResourceManager.GetString("TextStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Case.
        /// </summary>
        internal static string TitleCase {
            get {
                return ResourceManager.GetString("TitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train-Case.
        /// </summary>
        internal static string TrainCase {
            get {
                return ResourceManager.GetString("TrainCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPER CASE.
        /// </summary>
        internal static string UpperCase {
            get {
                return ResourceManager.GetString("UpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word frequency.
        /// </summary>
        internal static string WordFrequency {
            get {
                return ResourceManager.GetString("WordFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        internal static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
