name: Feature Request
description: Suggest an idea for a new feature or tool in DevToys
labels: feature, untriaged
body:
  - type: markdown
    attributes:
      value: |
        If you find this request relevant to you too, leave a thumbs up 👍

  - type: textarea
    attributes:
      label: What feature or new tool do you think should be added to DevToys?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why do you think this is needed?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution/Idea
      description: Describe your solution/idea. If possible, provide mock-up or example of how your idea could look like.

  - type: textarea
    attributes:
      label: Comments
      description: Additional information, comments or screenshots about the feature request.