namespace DevToys.Windows.Native;

[Flags]
public enum DWMWINDOWATTRIBUTE
{
    DWMWA_USE_IMMERSIVE_DARK_MODE = 20,
    DWMWA_SYSTEMBACKDROP_TYPE = 38,
    DWMWA_MICA_EFFECT = 1029,
    DWMWA_WINDOW_CORNER_PREFERENCE = 33
}
