version: '3.9'
services:
  devtoysgui:
    image: devtoysgui
    container_name: devtoysgui
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:Z
    devices:
      - /dev/dri
    network_mode: host
~
~
~
~
~
