//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Tools.Tools.Graphic.ColorBlindnessSimulator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorBlindnessSimulator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorBlindnessSimulator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Tools.Tools.Graphic.ColorBlindnessSimulator.ColorBlindnessSimulator", typeof(ColorBlindnessSimulator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Blindness Simulator tool.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate color blindness on a picture or screenshot.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuteranopia simulation.
        /// </summary>
        internal static string DeuteranopiaSimulation {
            get {
                return ResourceManager.GetString("DeuteranopiaSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file path to treat.
        /// </summary>
        internal static string InputOptionDescription {
            get {
                return ResourceManager.GetString("InputOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Blindness Simulator.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string OriginalPicture {
            get {
                return ResourceManager.GetString("OriginalPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory where the result should be persisted. By default, use input file&apos;s directory.
        /// </summary>
        internal static string OutputDirectoryOptionDescription {
            get {
                return ResourceManager.GetString("OutputDirectoryOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protanopia simulation.
        /// </summary>
        internal static string ProtanopiaSimulation {
            get {
                return ResourceManager.GetString("ProtanopiaSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tritanopia Protanopia Deuteranopia Dalton Daltonism Daltonist.
        /// </summary>
        internal static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Blindness Simulator.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides the progress of the hashing operation.
        /// </summary>
        internal static string SilentOptionDescription {
            get {
                return ResourceManager.GetString("SilentOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tritanopia simulation.
        /// </summary>
        internal static string TritanopiaSimulation {
            get {
                return ResourceManager.GetString("TritanopiaSimulation", resourceCulture);
            }
        }
    }
}
