//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Tools.Tools.Testers.JsonPathTester {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonPathTester {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonPathTester() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Tools.Tools.Testers.JsonPathTester.JsonPathTester", typeof(JsonPathTester).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSONPath Tester tool.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array slice operator.
        /// </summary>
        internal static string CheatSheetArraySliceOperator {
            get {
                return ResourceManager.GetString("CheatSheetArraySliceOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracket-notated child or children.
        /// </summary>
        internal static string CheatSheetBracketNotedChildOperator {
            get {
                return ResourceManager.GetString("CheatSheetBracketNotedChildOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for filter expressions. Refers to the current node for further processing..
        /// </summary>
        internal static string CheatSheetCurrentObjectElement {
            get {
                return ResourceManager.GetString("CheatSheetCurrentObjectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CheatSheetDescription {
            get {
                return ResourceManager.GetString("CheatSheetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot-notated child.
        /// </summary>
        internal static string CheatSheetDotNotedChildOperator {
            get {
                return ResourceManager.GetString("CheatSheetDotNotedChildOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects all elements in an object or array that match the specified boolean expression. Returns a list..
        /// </summary>
        internal static string CheatSheetFilterExpression {
            get {
                return ResourceManager.GetString("CheatSheetFilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs a deep scan for the specified property in all available objects. Always returns a list, even for a single match..
        /// </summary>
        internal static string CheatSheetRecursiveDescent {
            get {
                return ResourceManager.GetString("CheatSheetRecursiveDescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root object or array..
        /// </summary>
        internal static string CheatSheetRootObjectElement {
            get {
                return ResourceManager.GetString("CheatSheetRootObjectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script expression..
        /// </summary>
        internal static string CheatSheetScriptExpression {
            get {
                return ResourceManager.GetString("CheatSheetScriptExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the n-th element from an array. Indexes start from 0..
        /// </summary>
        internal static string CheatSheetSubscriptOperator {
            get {
                return ResourceManager.GetString("CheatSheetSubscriptOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        internal static string CheatSheetSyntax {
            get {
                return ResourceManager.GetString("CheatSheetSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat sheet.
        /// </summary>
        internal static string CheatSheetTitle {
            get {
                return ResourceManager.GetString("CheatSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects n1 and n2 array items. Returns a list..
        /// </summary>
        internal static string CheatSheetUnionOperator {
            get {
                return ResourceManager.GetString("CheatSheetUnionOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard. Selects all elements in an object or array, regardless of their names or indexes..
        /// </summary>
        internal static string CheatSheetWildcard {
            get {
                return ResourceManager.GetString("CheatSheetWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test a JSONPath.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file selected doesn&apos;t exist..
        /// </summary>
        internal static string InputFileNotFound {
            get {
                return ResourceManager.GetString("InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text or path to a file containing the JSON.
        /// </summary>
        internal static string InputJsonOptionDescription {
            get {
                return ResourceManager.GetString("InputJsonOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text or path to a file containing the JSONPath.
        /// </summary>
        internal static string InputJsonPathOptionDescription {
            get {
                return ResourceManager.GetString("InputJsonPathOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSONPath.
        /// </summary>
        internal static string InputJsonPathTitle {
            get {
                return ResourceManager.GetString("InputJsonPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        internal static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an input text or an input file.
        /// </summary>
        internal static string InvalidInputOrFileCommand {
            get {
                return ResourceManager.GetString("InvalidInputOrFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSONPath Tester.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found.
        /// </summary>
        internal static string NoMatchFound {
            get {
                return ResourceManager.GetString("NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the output file.
        /// </summary>
        internal static string OutputFileOptionDescription {
            get {
                return ResourceManager.GetString("OutputFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path json.
        /// </summary>
        internal static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSONPath.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
    }
}
