//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Tools.Tools.Formatters.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlFormatter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlFormatter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Tools.Tools.Formatters.Sql.SqlFormatter", typeof(SqlFormatter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Formatter tool.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Db2.
        /// </summary>
        internal static string Db2 {
            get {
                return ResourceManager.GetString("Db2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format SQL data.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 spaces.
        /// </summary>
        internal static string FourSpaces {
            get {
                return ResourceManager.GetString("FourSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation.
        /// </summary>
        internal static string Indentation {
            get {
                return ResourceManager.GetString("Indentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which indentation you want to use.
        /// </summary>
        internal static string IndentationOptionDescription {
            get {
                return ResourceManager.GetString("IndentationOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file selected doesn&apos;t exist..
        /// </summary>
        internal static string InputFileNotFound {
            get {
                return ResourceManager.GetString("InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text or path to a file containing the sql to format.
        /// </summary>
        internal static string InputOptionDescription {
            get {
                return ResourceManager.GetString("InputOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an input text or an input file.
        /// </summary>
        internal static string InvalidInputOrFileCommand {
            get {
                return ResourceManager.GetString("InvalidInputOrFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leading comma.
        /// </summary>
        internal static string LeadingComma {
            get {
                return ResourceManager.GetString("LeadingComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to use leading commas or not.
        /// </summary>
        internal static string LeadingCommaDescription {
            get {
                return ResourceManager.GetString("LeadingCommaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Formatter.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MariaDB.
        /// </summary>
        internal static string MariaDb {
            get {
                return ResourceManager.GetString("MariaDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL.
        /// </summary>
        internal static string MySql {
            get {
                return ResourceManager.GetString("MySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N1QL.
        /// </summary>
        internal static string N1ql {
            get {
                return ResourceManager.GetString("N1ql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 tab.
        /// </summary>
        internal static string OneTab {
            get {
                return ResourceManager.GetString("OneTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the output file.
        /// </summary>
        internal static string OutputFileOptionDescription {
            get {
                return ResourceManager.GetString("OutputFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL/SQL.
        /// </summary>
        internal static string PlSql {
            get {
                return ResourceManager.GetString("PlSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL.
        /// </summary>
        internal static string PostgreSql {
            get {
                return ResourceManager.GetString("PostgreSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon Redshift.
        /// </summary>
        internal static string RedShift {
            get {
                return ResourceManager.GetString("RedShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Formatter.
        /// </summary>
        internal static string SearchDisplayName {
            get {
                return ResourceManager.GetString("SearchDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark SQL.
        /// </summary>
        internal static string SparkSql {
            get {
                return ResourceManager.GetString("SparkSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SqlLanguage {
            get {
                return ResourceManager.GetString("SqlLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which SQL language to use.
        /// </summary>
        internal static string SqlLanguageDescription {
            get {
                return ResourceManager.GetString("SqlLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard SQL.
        /// </summary>
        internal static string StandardSql {
            get {
                return ResourceManager.GetString("StandardSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transact-SQL.
        /// </summary>
        internal static string TransactSql {
            get {
                return ResourceManager.GetString("TransactSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 spaces.
        /// </summary>
        internal static string TwoSpaces {
            get {
                return ResourceManager.GetString("TwoSpaces", resourceCulture);
            }
        }
    }
}
