//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Tools.Tools.Generators.Password {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasswordGenerator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordGenerator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Tools.Tools.Generators.Password.PasswordGenerator", typeof(PasswordGenerator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator tool.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigurationTitle {
            get {
                return ResourceManager.GetString("ConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random passwords.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit characters.
        /// </summary>
        internal static string Digits {
            get {
                return ResourceManager.GetString("Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use digit characters (0123456789).
        /// </summary>
        internal static string DigitsDescription {
            get {
                return ResourceManager.GetString("DigitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits.
        /// </summary>
        internal static string DigitsDescriptionStateOn {
            get {
                return ResourceManager.GetString("DigitsDescriptionStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the generated password can include digits characters (0123456789).
        /// </summary>
        internal static string DigitsOptionDescription {
            get {
                return ResourceManager.GetString("DigitsOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcludedCharacters.
        /// </summary>
        internal static string ExcludeCharacters {
            get {
                return ResourceManager.GetString("ExcludeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use the following characters to generate a password.
        /// </summary>
        internal static string ExcludeCharactersDescription {
            get {
                return ResourceManager.GetString("ExcludeCharactersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluding &apos;{0}&apos;.
        /// </summary>
        internal static string ExcludedCharactersDescriptionState {
            get {
                return ResourceManager.GetString("ExcludedCharactersDescriptionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of characters that should not be used to generate the password.
        /// </summary>
        internal static string ExcludedCharactersOptionDescription {
            get {
                return ResourceManager.GetString("ExcludedCharactersOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Password(s).
        /// </summary>
        internal static string GenerateButton {
            get {
                return ResourceManager.GetString("GenerateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GenerateTitle {
            get {
                return ResourceManager.GetString("GenerateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the password to generate.
        /// </summary>
        internal static string LengthOptionDescription {
            get {
                return ResourceManager.GetString("LengthOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase characters.
        /// </summary>
        internal static string Lowercase {
            get {
                return ResourceManager.GetString("Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use lowercase characters (abcdefghijkmnopqrstuvwxyz).
        /// </summary>
        internal static string LowercaseDescription {
            get {
                return ResourceManager.GetString("LowercaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        internal static string LowercaseDescriptionStateOn {
            get {
                return ResourceManager.GetString("LowercaseDescriptionStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the generated password can include lowercase characters (abcdefghijkmnopqrstuvwxyz).
        /// </summary>
        internal static string LowercaseOptionDescription {
            get {
                return ResourceManager.GetString("LowercaseOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string MultiplySymbol {
            get {
                return ResourceManager.GetString("MultiplySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password(s) can be generated because no options have been selected..
        /// </summary>
        internal static string NoCharacterSetsWarning {
            get {
                return ResourceManager.GetString("NoCharacterSetsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Passwords to generate.
        /// </summary>
        internal static string NumberOfPasswordsToGenerate_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("NumberOfPasswordsToGenerate_AutomationProperties_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passkey Secret Pwd.
        /// </summary>
        internal static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters.
        /// </summary>
        internal static string SpecialCharacters {
            get {
                return ResourceManager.GetString("SpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use special characters (!@#$%^&amp;*).
        /// </summary>
        internal static string SpecialCharactersDescription {
            get {
                return ResourceManager.GetString("SpecialCharactersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters.
        /// </summary>
        internal static string SpecialCharactersDescriptionStateOn {
            get {
                return ResourceManager.GetString("SpecialCharactersDescriptionStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the generated password can include special characters (!@#$%^&amp;*).
        /// </summary>
        internal static string SpecialCharactersOptionDescription {
            get {
                return ResourceManager.GetString("SpecialCharactersOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase characters.
        /// </summary>
        internal static string Uppercase {
            get {
                return ResourceManager.GetString("Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use uppercase characters (ABCDEFGHJKLMNOPQRSTUVWXYZ).
        /// </summary>
        internal static string UppercaseDescription {
            get {
                return ResourceManager.GetString("UppercaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        internal static string UppercaseDescriptionStateOn {
            get {
                return ResourceManager.GetString("UppercaseDescriptionStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the generated password can include uppercase characters (ABCDEFGHJKLMNOPQRSTUVWXYZ).
        /// </summary>
        internal static string UppercaseOptionDescription {
            get {
                return ResourceManager.GetString("UppercaseOptionDescription", resourceCulture);
            }
        }
    }
}
